### PR TITLE
Chapter 3.2

### PR DESCRIPTION
**Pull request by DentFuse**
Added a chapter to teach how to handle friend messages and reply with specific messages. Also, there is only one commit (c0b43d4), idk how I added the other commits, new to git xD Please only merge that one.

### CODE REVIEW

**Comment by andrewda** [comment]
Thanks a ton! I will check it out in a bit and makes some edits :)

**Comment by DentFuse** [comment]
@andrewda Fixed all issues as noted by codacy

**Comment by DentFuse** [comment]
@andrewda Any more edits to do?

**Comment by DentFuse** [comment]
@andrewda 14 Days have passed since I opened this, anything left to do? Why is this taking so long?

**Comment by xmwx38** [comment]
You oughta add "**Chapter 3.2**" to the **title** of this thread =)

~David, your friend~

**Comment by DentFuse** [comment]
@xmwx38 Done ;)

**Comment by xmwx38** [comment]
Nice job on your pull request, @DentFuse.

**Comment by DentFuse** [comment]
@andrewda -_-  What's taking so long?

**Comment by xmwx38** [comment]
@DentFuse Submit a pull request for our forked version of [node-steam-guide](https://github.com/Steam-Bot-Basics/node-steam-guide).
We seem to have more time & motivation to keep this project going, than @andrewda.

**Comment by DentFuse** [comment]
Sure @xmwx38, will do :smile:

**Pull request closed without merging**
